### ISSUE TITLE
high throughput reliability

### ISSUE THREAD

**Issue by Byter09** [amethyst/laminar#134] opened 2018-12-29 20:43 UTC
Hello everyone.

I'm writing a small tool to verify this paper: https://arxiv.org/pdf/1302.1479.pdf
The implementation is pretty easy. There is a master distributing jobs and several slaves receiving jobs and sending back results.
I used/abused `laminar` for my usecase, because UDP seemed like the perfect choice for sending whole messages and all the fancy features like message-splitting and reliability were just the icing on top. It also made using `bincode` very easy and reliable.

I put my tool online so people can look at the code: https://gitlab.com/byter/csr-distributed
You can start a master by running `cargo run -- 3` and connect a slave by running `cargo run -- localhost:42111`. Be warned, there are a lot of debugging messages in there so it might be a bit spam-y. You can change the logging level by appending a `info` parameter or whatever level you want. Also no threading (a slave for each core) or clean-up happened yet - I hope this is excusable :D

Now to the actual issue:
When running a `master` with higher integers (for example the paper is for `9`, which would take weeks with a single slave) the job amount rises exponentially. This of course causes transmission rates to be way higher.
Using `5` alone causes it to return
https://github.com/amethyst/laminar/blob/b9564ffeb5b56e020767246a5536a6cadb407504/src/net/connection/virtual_connection.rs#L94

@TimonPost suggested on discord, this might be due to the sheer amount of data being transmitted and packets being dropped - including the header. So I investiged this a bit.

The last reported numbers by the slave were 
```
SENT PCKTS: sum: 33468 | pps: 293 | record pps: 2802
RECV PCKTS: sum: 33467 | pps: 292 | record pps: 2801

SENT BYTES: sum: 3301537 | bps: 29211 | record bps: 278766
RECV BYTES: sum: 1335351 | bps: 11795 | record bps: 112245
```
before it returned that error.

The corresponding master numbers:
```
SENT PCKTS: sum: 33467 | pps: 292 | record pps: 2801
RECV PCKTS: sum: 33467 | pps: 292 | record pps: 2801

SENT BYTES: sum: 1803889 | bps: 15883 | record bps: 151459
RECV BYTES: sum: 2832901 | bps: 25025 | record bps: 239454
```

Note: `bps` stands for `bytes per second` and  `pps` for `packets per second`
These values also directly come from `socket.recv()` and `socket.send()` and sending is done using the `ReliableUnordered` delivery method (because ReliableOrdered is not yet available).

As you can see these numbers do not line up and indicate packet drop. I'm no expert in this so I can not really identify it yet... hence this issue and a cry for help. :yum: 

Additional notes:
- It's called `MeshClient` because in the end I also want slaves to communicate and exchange jobs.
- Obviously the implementation of sending and receiving messages is the same in both clients.
- I could've simply ignored such an error and do not respond to a request (which would let it time out), but this also happens with responses which do not receive an ACK or anything because I believe `laminar` does this already?
- I basically build a protocol on top of laminar, which is on top of UDP. Lots of places errors can pop up. If there's anything I did not catch yet, please tell me.
- `NetworkQuality` has no `#[derive(Debug)]` and made debugging it very hard, which is why I'm translating its values to `bool`. Turns out this is not even used in `laminar`...

**Comment by TimonPost** [comment] 2018-12-29 21:05
The error ProtocolVersionMismach is only occring when the other side tries to connect whit an older version of laminar. Since  you are using the same version of laminar for everything I suspect the header packet bystes are not correct. This should not go wrong that's why expected that there is some packet loss going on.

**Comment by Byter09** [comment] 2018-12-30 00:00
[csr_communication.tar.gz](https://github.com/amethyst/laminar/files/2716796/csr_communication.tar.gz)
I tried triggering it again and recorded it this time. This file includes a `*.pcapng` with the last few packets being exchanged before the slave reports the issue. The master seems to be sending out a malformed header?

Also in case it helps, here's my basic system configuration:
![systeminfo](https://user-images.githubusercontent.com/16060697/50543119-3f056f00-0bce-11e9-93c2-9f7d77885d06.png)

**Comment by LucioFranco** [comment] 2019-01-19 16:37
huh interesting, it would make sense that the buffer becomes full to a certain degree at least on linux the defaults are quite low. @TimonPost any ideas?

**Comment by TimonPost** [comment] 2019-01-19 18:35
Example date for failing packet: 
```
Received Data: [1, 2, 3, 41, 2, 3, 41, 2, 3, 41, 2, 3, 41, 2, 3, 41, 2, 3, 4], 
expected proto number: 1072040592, 
received proto number: 16909097'
```

**Comment by TimonPost** [comment] 2019-01-19 18:42
Data of the 5 previous packets and the failing one:

```
[63, 230, 10, 144, 0, 2, 132, 12, 1, 81, 255, 255, 255, 255, 1, 2, 3, 41, 2, 3, 41, 2, 3, 41, 2, 3, 41, 2, 3, 41, 2, 3, 4]
[63, 230, 10, 144, 0, 2, 132, 26, 1, 81, 255, 255, 255, 255, 1, 2, 3, 41, 2, 3, 41, 2, 3, 41, 2, 3, 41, 2, 3, 41, 2, 3, 4]
[63, 230, 10, 144, 0, 2, 132, 52, 1, 81, 255, 255, 255, 255, 1, 2, 3, 41, 2, 3, 41, 2, 3, 41, 2, 3, 41, 2, 3, 41, 2, 3, 4]
[63, 230, 10, 144, 0, 2, 132, 77, 1, 81, 255, 255, 255, 255, 1, 2, 3, 41, 2, 3, 41, 2, 3, 41, 2, 3, 41, 2, 3, 41, 2, 3, 4]
[63, 230, 10, 144, 0, 2, 132, 100, 1, 81, 255, 255, 255, 255, 1, 2, 3, 41, 2, 3, 41, 2, 3, 41, 2, 3, 41, 2, 3, 41, 2, 3, 4]
[1, 2, 3, 41, 2, 3, 41, 2, 3, 41, 2, 3, 41, 2, 3, 41, 2, 3, 4]
```

**Comment by jstnlef** [comment] 2019-01-19 22:04
I can confirm I'm seeing the same error on my Mac.

**Comment by CosineP** [comment] 2019-04-16 08:59
i think this is an even more generic problem: i don't think `reliable_unordered` is fulfilling its contract. see https://gist.github.com/CosineP/52e5068375bd1ea11374fc4dac34c1d3

**Comment by pakipaki2000** [comment] 2019-04-21 08:22
Hi,

Does it mean that I can't use this library to do file transfer? (64KB around)
I was planning to use it instead of TCP.

Thanks! :)

**Comment by TimonPost** [comment] 2019-04-21 11:22
We did some fixes with #176 around reliable transferring of data, it had a few bugs and the patch will be released soon. If files are the only things you are sending I would consider TCP. We've got to test if this issue is solved by #176.

**Comment by pakipaki2000** [comment] 2019-04-21 11:33
Thanks for the reply Timon! 

Even for small files (<64KB) you would go for TCP?

**Comment by TimonPost** [comment] 2019-04-21 12:11
Yea, you need reliable data, and TCP is exactly meant for that. First, laminar is not originally meant for file transfer but for game networking where fast communication is required, secondly, we haven't actually done a test with those sizes yet. You can try it out and be the first one to report if your file arrived completely. If I was you I would consider using laminar only when you want to send a file with data between all the other game data your sending, because you've already opened a laminar socket.

**Comment by pakipaki2000** [comment] 2019-04-22 00:37
Thanks for your input

**Comment by TimonPost** [comment] 2019-07-06 15:32
#219 explains how and when to use laminar for reliability. Secondly, I am not sure if this is still a problem, thirdly, there have been a lot of updates around this code. The new issue can be created if needed.

**Closed by TimonPost** 2019-07-06 15:32 UTC
