### ISSUE TITLE
Sending too many packets at once causes packet corruption

### ISSUE THREAD

**Issue by zesterer** [amethyst/laminar#180] opened 2019-04-26 18:30 UTC
I don't really have any specific information about this issue, other than that sending a few hundred 1K packets at once causes packet corruption. I would have imagined that `laminar` would automatically handle high throughput like this and not allow data through fast enough to cause packet corruption.

**Comment by TimonPost** [comment] 2019-04-26 20:39
I think that this is a duplicate of #134. Hopefully, this is solved by resenting changes we made an still are making: #177. If that code is merged we will definably research this issue further.

Can you report in that issue the following information:
- Platform
- Reliability / Ordering packet type
- Payload size

**Closed** 2019-04-26 20:39 UTC
