### ISSUE TITLE
Enable deny attributes

### ISSUE THREAD

**Issue by LucioFranco** [amethyst/laminar#72] opened 2018-10-28 17:08 UTC
This issue is to track the progress of denying warnings / missing docs.

- [ ] deny warnings on CI
- [ ] warn for missing docs on public interfaces

**Comment by torkleyy** [comment] 2018-11-03 16:53
Partial duplicate of #80

**Comment by torkleyy** [comment] 2018-11-03 17:04
Copy from #80

I recommend enabling a warning instead and denying all warnings on CI, similar to what we've done in the Amethyst main repository.

**Comment by torkleyy** [comment] 2018-11-05 04:14
## Task

Amethyst uses a bot called bors to merge its PRs safely. For that, the branch gets merged with `master` into another branch and is tested separately by Travis. We want that this test fails if warnings are enabled. You can look up in amethyst/amethyst how this can be done.

Please make sure we still can compile code without docs locally. It should only stop us from merging such code into master.

**Comment by TimonPost** [comment] 2018-11-09 10:49
See: #90

**Comment by LucioFranco** [comment] 2018-11-09 14:55
Lets keep this open until that PR gets merged at least

**Closed** 2018-11-10 23:52 UTC
Labels: enhancement, good first issue
